### ISSUE TITLE
Ramdom URLs

### ISSUE THREAD

**Issue by agoncal** [mdeanda/lorem#3]
It would be nice to have a `Lorem.getURL()` that returns a random URL (based on a set of based URL, such as bit.ly, google.com, yahoo.com.....). 

And, why not, having a `Lorem.getURL(int min, int max)` that would return a random number of query parameters. For example, calling `Lorem.getURL(1, 2)` could return `http://www.google.com?lorem=ipsum&sit=amet`

**Comment by mdeanda** [comment]
added a basic implementation that generates working (?) google/bing/yahoo/duckduckgo urls using single word searches for now.
