### ISSUE TITLE
Ramdom Email addresses

### ISSUE THREAD

**Issue by agoncal** [mdeanda/lorem#4]
It would be nice to have a `Lorem.getEmail()` that returns a random email address (based on a set of firstname, lastname and domain URL, such as gmail.com, yahoo.com.....).

**Comment by mdeanda** [comment]
my concern with this is accidentally sending out emails. maybe i'll hard-code to @example.com ?

**Comment by agoncal** [comment]
Good point. You could use @example.com, @dummy.co.uk, @foo.bar.com

**Comment by mdeanda** [comment]
added with @example.com for now. might revisit later when i have time.

note: i've also refactored the library quite a bit and the next release wont really be compatible with the older one but it should be simple enough to update.
