### ISSUE TITLE
Ramdom Cities

### ISSUE THREAD

**Issue by agoncal** [mdeanda/lorem#5]
It would be nice to have a `Lorem.getCity()` that returns a random city (based on a list of cities). This would be complementary to `Lorem.getStateAbbr()`and `Lorem.getZipCode()`

**Comment by mdeanda** [comment]
Good idea !

**Comment by mdeanda** [comment]
actually just looked at latest version and its already in, just never cut a release from it on maven.

**Comment by agoncal** [comment]
Cool ;o)
